### ISSUE TITLE
Common introductory text

### ISSUE THREAD

**Issue by karinbredenberg** [DILCISBoard/GroupDocumentation#17]
This text is suggested as the common introduction: 

This is a specification maintened by the Digital information LifeCycle Interoperability Standards Board (DILCIS Board, http://dilcis.eu/) The board was created to enhance and maintain the draft specifications developed in the European Archival Records and Knowledge Preservation Project (E-ARK project http://eark-project.com/ ) ending in January 2017. The Board consist of 8 members with no limitation of others taking part in the work. All board documents and specifications is stored in GitHub https://github.com/DILCISBoard and published versions are presented on the board webpage. Since 2018 the DILCIS Board is the responsible body for the core specifications in the Connection Europé Facility Bulding Block eArchiving https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eArchiving . The specifications are using the Open Archvial Information System Reference Model (OAIS Reference Model, ISO 14721:2012 (CCSDS 650.0-M-2) https://www.iso.org/standard/57284.html )
The specifications are diveded into two groups of types. 
1.	The Common Specification for Information Packages with extensions for E-ARK SIP, E-ARK AIP and E-ARK DIP which are the primary specifications for describing a transfer of information. This specification is always used togheter with a CITS.
2.	Content Information Type Specifications (CITS) which describes the content as well as how to place it in a Information Package. A CITS can be created by the board or be endorsed by the board and created by other interest groups with a speciality in a content information type thus making sure its the specialists creating the CITS. 

In appendix 1 a full list of contributors to this specification as well as the revision history is found.

**Comment by jmaferreira** [comment]
Fixed a few typos on the text:

This is a specification maintained by the Digital information LifeCycle Interoperability Standards Board (DILCIS Board, http://dilcis.eu/) The board was created to enhance and maintain the draft specifications developed in the European Archival Records and Knowledge Preservation Project (E-ARK project http://eark-project.com/ ) ending in January 2017. The Board consist of 8 members with no limitation of others taking part in the work. All board documents and specifications are stored in GitHub (https://github.com/DILCISBoard) and published versions are presented on the board webpage. Since 2018 the DILCIS Board is the responsible body for the core specifications in the Connection Europe Facility Building Block eArchiving (https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eArchiving) . The specifications are using the Open Archival Information System Reference Model (OAIS Reference Model, ISO 14721:2012 (CCSDS 650.0-M-2) https://www.iso.org/standard/57284.html).

The specifications are divided into two groups of types. 

1.	The Common Specification for Information Packages with extensions for E-ARK SIP, E-ARK AIP and E-ARK DIP which are the primary specifications for describing a transfer of information. This specification is always used together with a CITS.
2.	Content Information Type Specifications (CITS) which describes the content as well as how to place it in an Information Package. A CITS can be created by the board or be endorsed by the board and created by other interest groups with a speciality in a content information type thus making sure the specialists are creating the CITS. 

In appendix 1 a full list of contributors to this specification as well as the revision history is found.

**Comment by jmaferreira** [comment]
This is somewhat of a preface and should be included in the documents by means of the auto PDF generator.

**Comment by AnjaPaulic** [comment]
Odsoten sem do 24. 04. 2019.

Do 24. 4. 2019 sem odsotna. Če odgovor nujno potrebujete, se obrnite na
ars@gov.si.

Lep pozdrav,

Anja Paulič

I am out of the office until 24th of April 2019. If you need immediate
answer, please contact ars@gov.si.

Regards,

Anja Paulič


Opomba: To je samodejni odgovor na vaše sporočilo  "Re:
[DILCISBoard/GroupDocumentation] Common introductory text (#17)" poslano
naprej  23.04.2019 15:35:45.

To je edino sporočilo, ki ga boste prejeli, ko je oseba odsotna.

**Comment by AnjaPaulic** [comment]
Odsoten sem do 24. 04. 2019.

Do 24. 4. 2019 sem odsotna. Če odgovor nujno potrebujete, se obrnite na
ars@gov.si.

Lep pozdrav,

Anja Paulič

I am out of the office until 24th of April 2019. If you need immediate
answer, please contact ars@gov.si.

Regards,

Anja Paulič


Opomba: To je samodejni odgovor na vaše sporočilo  "Re:
[DILCISBoard/GroupDocumentation] Common introductory text (#17)" poslano
naprej  23.04.2019 15:38:29.

To je edino sporočilo, ki ga boste prejeli, ko je oseba odsotna.

**Comment by DrJaime** [comment]
I have corrected a few more typos:

This specification is maintained by the Digital Information LifeCycle Interoperability Standards Board (DILCIS Board, http://dilcis.eu/). The DILCIS Board was created to enhance and maintain the draft specifications developed in the European Archival Records and Knowledge Preservation Project (E-ARK project, http://eark-project.com/) which concluded in January 2017. The Board consists of eight members, but there is no limitation on the number of participants taking part in the work. All Board documents and specifications are stored in GitHub (https://github.com/DILCISBoard) while published versions are made available on the Board webpage. Since 2018 the DILCIS Board has been responsible for the core specifications in the Connecting Europe Facility eArchiving Building Block  https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eArchiving). These specifications use the Open Archival Information System Reference Model (OAIS Reference Model, ISO 14721:2012 [CCSDS 650.0-M-2] https://www.iso.org/standard/57284.html).

There are two types of specifications:
1.	The Common Specifications for Information Packages with extensions for E-ARK SIP, E-ARK AIP and E-ARK DIP, are the primary specifications for describing the transfer of information. This specification is always used together with a CITS.
2.	The Content Information Type Specifications (CITS) describe both the content and how to place it in an Information Package. A CITS can either be created by the Board or be created by other interest groups with a speciality in specific a content information type and then be endorsed by the Board. This ensures that relevant specialists create the CITS.

A full list of contributors to this specification, as well as the revision history can be found in Appendix 1.

**Comment by PhillipTommerholt** [comment]
I definitely agree that the organizational part and details should be included in the common introduction, but I think that the most important should come first: the goal and the aim for the specification(s). 

The goal/aim in the previous CSIP was this:
![image](https://user-images.githubusercontent.com/15984159/56945237-c33d1400-6b26-11e9-9cb5-f93634b08245.png)

I think we can improve this former text so it fits all specifications, but it is still my understanding that goals 1,2 and the "ultimate goal" are the goals and aims for the specifications today?

**Comment by PhillipTommerholt** [comment]
_What about something like this?_

___

**1  Aim with the specification**

This specification is one of several interconnected specifications. The single most important aim and goal for all of the specifications combined is the provision of a common set of specifications for packaging digital information for archiving purposes. The specifications are based on common, international standards for transmitting, describing and preserving digital data. They are created to help data creators, software developers and digital archives to tackle the challenge of short, medium and long-term data management and reuse in a sustainable, authentic, cost-efficient, manageable and interoperable way. 

The main standard which the specifications make use of and is built upon is the Reference model for an Open Archival Information System (OAIS)  ([OAIS Reference model](https://www.iso.org/standard/57284.html)) which has Information Packages as its basis. Familiarity with the core functional entities of OAIS is a prerequisite for understanding the specifications.  

A visualization of the current specification network can be seen here:

![image](https://user-images.githubusercontent.com/15984159/57220780-e838f780-6ffc-11e9-9a2b-0cef765f9d29.png)

The purposes of the individual specifications (including this one) can be seen in the following table:


<table>
  <tr>
   <td>Specification
   </td>
   <td>Aim and goals
   </td>
  </tr>
  <tr>
   <td>Common Specification for Information Packages
   </td>
   <td>This document introduces the concept of a Common Specification for Information Packages. It aims to serve three main purposes: 
<ul>

<li>Establish a common understanding of the requirements which need to be met in order to achieve interoperability of Information Packages; 

<li>Establish a common base for the development of more specific Information Package definitions and tools within the digital preservation community; 

<li>Propose the details of an XML-based implementation of the requirements using, to the largest possible extent, standards which are widely used in international digital preservation. 

<p>
Ultimately the goal of the Common Specification is to reach a level of interoperability between all Information Packages so that tools implementing the Common Specification can be taken up by institutions without needing major modifications or adaptations. 
</li>
</ul>
   </td>
  </tr>
  <tr>
   <td>E-ARK SIP
   </td>
   <td>The main aims and goals of this specification are to:
<ul>

<li>Define the general structure for a Submission Information Package format in a way that it is suitable for a wide variety of archival scenarios, e.g. document and image collections, databases or geographical data;

<li>Enhance interoperability between Producers and Archives;

<li>Recommend best practices regarding metadata, content and structure of Submission Information Packages.
</li>
</ul>
   </td>
  </tr>
  <tr>
   <td>E-ARK AIP
   </td>
   <td>The main aims and goals of this specification are to:
<ul>

<li>To define a generic structure of the AIP format in a way that it is suitable for a wide variety of data types, such as document and image collections, archival records, databases or geographical data.

<li>To recommend a set of metadata related to the structural and the preservation aspects of the AIP as implemented by the reference implementation (earkweb).

<li>To ensure the format is also suitable to store large quantities of data.
</li>
</ul>
   </td>
  </tr>
  <tr>
   <td>E-ARK DIP
   </td>
   <td>The main aims and goals of this specification are to:
<ul>

<li>To define a generic structure of the DIP format in a way that it is suitable for a wide variety of archival records, such as document and image collections, databases or geographical data.

<li>To recommend a set of metadata related to the structural and the access aspects of the DIP.
</li>
</ul>
   </td>
  </tr>
  <tr>
   <td>Content Information Type Specifications
   </td>
   <td>The main aim and goal of a Content Information Type Specification is to:
<ul>

<li>define in technical terms how data and metadata must be formatted and placed within a CS IP Information Package in order to achieve interoperability in exchanging specific Content Information.

<p>
The number of possible Content Information Type Specifications is potentially unlimited. For at list of existing Content Information Type Specifications see [link], and read more about  Content Information Type Specifications in the Common Specification for Information Packages [link].
</li>
</ul>
   </td>
  </tr>
</table>
 
**2 Organizational anchorage**

This specification is maintained by the Digital Information LifeCycle Interoperability Standards Board (DILCIS Board, [http://dilcis.eu/](http://dilcis.eu/)). The DILCIS Board was created to enhance and maintain the draft specifications developed in the European Archival Records and Knowledge Preservation Project (E-ARK project, [http://eark-project.com/](http://eark-project.com/)) which concluded in January 2017. The Board consists of eight members, but there is no limitation on the number of participants taking part in the work. All Board documents and specifications are stored in GitHub ([https://github.com/DILCISBoard](https://github.com/DILCISBoard)) while published versions are made available on the Board webpage. Since 2018 the DILCIS Board has been responsible for the core specifications in the Connecting Europe Facility eArchiving Building Block[https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eArchiving](https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/eArchiving)). 

**3 Authors**

A full list of contributors to this specification, as well as the revision history can be found in Appendix 1.

___

_I have made a [Google Docs](https://docs.google.com/document/d/1YBpYR9E_gG6odhTQZac-ZQFJvtLWJLp_8zlCG89gVJA/edit) where this text can be found. We could use this thread to discuss my proposed text and/or make comments in the Google Docs. I think a "specification landscape overview" which all the specifications share is important for coherence purposes. The goals of the different specifications should always be looked at in total and not be isolated for the CSIP alone._

**Comment by karinbredenberg** [comment]
Adds Miguels commetn here too: 

Points of standardisation between specs:
List of authors and reviewers (at least the way this information is presented)
History of the specification
Spec map or guide through the entire set of specifications
Overall design including cover and images
Section names and order

**Comment by jmaferreira** [comment]
@karinbredenberg is @PhillipTommerholt texts approved? Can we integrate it?

Just a few comments:

1. instead of "Aim with the specification" I would suggest "Relationship to other E-ARK specifications"
2. I rather see the authors in the second page (begins the front cover) than in an appendix.

**Comment by jmaferreira** [comment]
I've tried to follow the CSIP structure and ended up with this index:

I. ​Acknowledgements
II. ​Contact & Feedback
III. ​Authors
IV. ​Revision History
V. Relationship to other E-ARK specifications

1. Introduction
1.2 Scope and purpose
1.3 Target audience
1.4 Definition of an SIP

2. Structure
3. METS

...and so on...

**Comment by karinbredenberg** [comment]
This is not solved. We need to work more with this question but that has to be for the next release of the specifications. One thing to have in mind is that we need to create an overall introduction to all the specifications meaning this text will be better placed there. We can't repeat all in all specification.

**Comment by AnjaPaulic** [comment]
Odsoten sem do 27. 05. 2019.

Do 27. 5. 2019 bom imela omejen dostop do elektronske pošte. Če odgovor
nujno potrebujete, se obrnite na ars@gov.si.

Lep pozdrav,

Anja Paulič

I will not be able to check my email on regular basis until 27th of May
2019. If you need immediate answer, please contact ars@gov.si.

Regards,

Anja Paulič


Opomba: To je samodejni odgovor na vaše sporočilo  "Re:
[DILCISBoard/GroupDocumentation] Common introductory text (#17)" poslano
naprej  15.05.2019 8:36:33.

To je edino sporočilo, ki ga boste prejeli, ko je oseba odsotna.

**Comment by AnjaPaulic** [comment]
Odsoten sem do 27. 05. 2019.

Do 27. 5. 2019 bom imela omejen dostop do elektronske pošte. Če odgovor
nujno potrebujete, se obrnite na ars@gov.si.

Lep pozdrav,

Anja Paulič

I will not be able to check my email on regular basis until 27th of May
2019. If you need immediate answer, please contact ars@gov.si.

Regards,

Anja Paulič


Opomba: To je samodejni odgovor na vaše sporočilo  "Re:
[DILCISBoard/GroupDocumentation] Common introductory text (#17)" poslano
naprej  15.05.2019 8:42:28.

To je edino sporočilo, ki ga boste prejeli, ko je oseba odsotna.

**Comment by karinbredenberg** [comment]
There is a common introduction used. It is placed in the specification publisher repository.
